apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    apps: demo-app
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
           
